$('.owl-carousel').owlCarousel({
    loop:true,
    margin:15,
    nav:false,  
    responsive:{
        0:{
            items:2.5
        },
        600:{
            items:4.5
        },
        1000:{
            items:6.5
        }
    }
})